CONFIG_INPUT=y
CONFIG_ZMK_EXT_POWER=y

# dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

# Enable custom dongle display with widgets
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y
CONFIG_ZMK_DONGLE_DISPLAY_BONGO_CAT=y
CONFIG_ZMK_DONGLE_DISPLAY_MODIFIERS=y
CONFIG_ZMK_DONGLE_DISPLAY_LAYER=y
CONFIG_ZMK_DONGLE_DISPLAY_WPM=y
